import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchReceipts } from "./receiptsSlice";
import ReceiptForm from "./ReceiptForm";

const AdminReceipts = () => {
  const dispatch = useDispatch();
  const { receipts, loading, error } = useSelector((state) => state.receipts);

  useEffect(() => {
    dispatch(fetchReceipts());
  }, [dispatch]);

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-4 text-center">Admin - All Receipts</h1>

      <ReceiptForm />

      {loading && <p className="text-center mt-4">Loading receipts...</p>}
      {error && <p className="text-red-500 text-center mt-4">{error}</p>}

      <div className="mt-6">
        {receipts.map((receipt) => (
          <div
            key={receipt._id}
            className="bg-gray-100 rounded shadow p-4 mb-4"
          >
            <p><strong>Receipt ID:</strong> {receipt._id}</p>
            <p><strong>Amount:</strong> ${receipt.amount}</p>
            <p><strong>Date:</strong> {new Date(receipt.date).toLocaleDateString()}</p>
            <p><strong>Session:</strong> {receipt.sessionId}</p>
            <p><strong>Generated By:</strong> {receipt.generatedBy}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AdminReceipts;
